import { v4 as uuidv4 } from "uuid";

import { BulletsProps } from "@/types/bulletsData";

const traditionalIcedBullets: BulletsProps = {
  id: uuidv4(),
  title: `Balas Geladas Tradicionais`,
  description: `Balas de coco geladas tradicionais`,
  flavors: [
    {
      id: uuidv4(),
      name: `Amendoim`,
      description: undefined,
      price: 68,
      medias: null,
    },
    {
      id: uuidv4(),
      name: `Café`,
      description: undefined,
      price: 65,
      medias: null,
    },
    {
      id: uuidv4(),
      name: `Chocolate`,
      description: undefined,
      price: 65,
      medias: null,
    },
    {
      id: uuidv4(),
      name: `Limão`,
      description: undefined,
      price: 65,
      medias: null,
    },
    {
      id: uuidv4(),
      name: `Morango`,
      description: undefined,
      price: 65,
      medias: null,
    },
    {
      id: uuidv4(),
      name: `Nozes`,
      description: undefined,
      price: 80,
      medias: null,
    },
    {
      id: uuidv4(),
      name: `Tradicional`,
      description: undefined,
      price: 65,
      medias: null,
    },
  ],
  batters: null,
  chocolates: null,
  quantityOptions: [
    {
      id: uuidv4(),
      type: `Receita inteira`,
      mass: `1Kg`,
      quantity: 120,
      price: undefined,
    },
    {
      id: uuidv4(),
      type: `Meia receita`,
      mass: `500g`,
      quantity: 60,
      price: 48,
    },
  ],
  colorOptions: null,
};

const traditionalDryBullets: BulletsProps = {
  id: uuidv4(),
  title: `Balas Sequinhas Tradicionais`,
  description: `Balas de coco sequinhas tradicionais`,
  flavors: [
    {
      id: uuidv4(),
      name: `Amendoim`,
      description: undefined,
      price: 55,
      medias: null,
    },
    {
      id: uuidv4(),
      name: `Café`,
      description: undefined,
      price: 55,
      medias: null,
    },
    {
      id: uuidv4(),
      name: `Chocolate`,
      description: undefined,
      price: 55,
      medias: null,
    },
    {
      id: uuidv4(),
      name: `Limão`,
      description: undefined,
      price: 55,
      medias: null,
    },
    {
      id: uuidv4(),
      name: `Morango`,
      description: undefined,
      price: 55,
      medias: null,
    },
    {
      id: uuidv4(),
      name: `Nozes`,
      description: undefined,
      price: 65,
      medias: null,
    },
    {
      id: uuidv4(),
      name: `Tradicional`,
      description: undefined,
      price: 55,
      medias: null,
    },
  ],
  batters: null,
  chocolates: null,
  quantityOptions: [
    {
      id: uuidv4(),
      type: `Receita inteira`,
      mass: `1Kg`,
      quantity: 220,
      price: undefined,
    },
    {
      id: uuidv4(),
      type: `Meia receita`,
      mass: `500g`,
      quantity: 110,
      price: 40,
    },
  ],
  colorOptions: null,
};

const stuffedIcedBullets: BulletsProps = {
  id: uuidv4(),
  title: `Balas Geladas Recheadas`,
  description: `Balas de coco geladas recheadas`,
  flavors: [
    {
      id: uuidv4(),
      name: `Bicho de pé (Brigadeiro de Morango)`,
      description: undefined,
      price: 105,
      medias: null,
    },
    {
      id: uuidv4(),
      name: `Brigadeiro de cereja`,
      description: undefined,
      price: 105,
      medias: null,
    },
    {
      id: uuidv4(),
      name: `Brigadeiro branco`,
      description: undefined,
      price: 105,
      medias: null,
    },
    {
      id: uuidv4(),
      name: `Brigadeiro de beijinho`,
      description: undefined,
      price: 105,
      medias: null,
    },
    {
      id: uuidv4(),
      name: `Brigadeiro de cranberry com frutas cristalizadas`,
      description: undefined,
      price: 110,
      medias: null,
    },
    {
      id: uuidv4(),
      name: `Brigadeiro de leite ninho`,
      description: undefined,
      price: 105,
      medias: null,
    },
    {
      id: uuidv4(),
      name: `Brigadeiro de limão`,
      description: undefined,
      price: 105,
      medias: null,
    },
    {
      id: uuidv4(),
      name: `Brigadeiro de oreo`,
      description: undefined,
      price: 105,
      medias: null,
    },
    {
      id: uuidv4(),
      name: `Brigadeiro de pistache`,
      description: undefined,
      price: 110,
      medias: null,
    },
    {
      id: uuidv4(),
      name: `Brigadeiro tradicional`,
      description: undefined,
      price: 105,
      medias: null,
    },
    {
      id: uuidv4(),
      name: `Camafeu (Brigadeiro de Nozes)`,
      description: undefined,
      price: 110,
      medias: null,
    },
    {
      id: uuidv4(),
      name: `Doce de abacaxi`,
      description: undefined,
      price: 110,
      medias: null,
    },
    {
      id: uuidv4(),
      name: `Doce de damasco`,
      description: undefined,
      price: 105,
      medias: null,
    },
    {
      id: uuidv4(),
      name: `Goiabada`,
      description: undefined,
      price: 105,
      medias: null,
    },
    {
      id: uuidv4(),
      name: `Nutella`,
      description: undefined,
      price: 105,
      medias: null,
    },
    {
      id: uuidv4(),
      name: `Brigadeiro Tradicional com Cerejas`,
      description: undefined,
      price: 110,
      medias: null,
    },
    {
      id: uuidv4(),
      name: `Nutella com Amêndoas Laminadas`,
      description: undefined,
      price: 110,
      medias: null,
    },
    {
      id: uuidv4(),
      name: `Brigadeiro de Leite Ninho com Amêndoas Laminadas`,
      description: undefined,
      price: 110,
      medias: null,
    },
  ],
  batters: [
    `Amendoim`,
    `Café`,
    `Chocolate`,
    `Limão`,
    `Morango`,
    `Nozes`,
    `Tradicional`,
  ],
  chocolates: null,
  quantityOptions: [
    {
      id: uuidv4(),
      type: `Receita inteira`,
      mass: `1Kg`,
      quantity: 120,
      price: undefined,
    },
    {
      id: uuidv4(),
      type: `Meia receita`,
      mass: `500`,
      quantity: 60,
      price: 74,
    },
    {
      id: uuidv4(),
      type: `Receita inteira com 2 sabores diferentes`,
      mass: `1Kg`,
      quantity: 120,
      price: 120,
    },
  ],
  colorOptions: null,
};

const stuffedDryBullets: BulletsProps = {
  id: uuidv4(),
  title: `Balas Sequinhas Recheadas`,
  description: `Balas de coco sequinhas recheadas`,
  flavors: [
    {
      id: uuidv4(),
      name: `Bicho de pé (Brigadeiro de Morango)`,
      description: undefined,
      price: 105,
      medias: null,
    },
    {
      id: uuidv4(),
      name: `Brigadeiro de cereja`,
      description: undefined,
      price: 105,
      medias: null,
    },
    {
      id: uuidv4(),
      name: `Brigadeiro branco`,
      description: undefined,
      price: 105,
      medias: null,
    },
    {
      id: uuidv4(),
      name: `Brigadeiro de beijinho`,
      description: undefined,
      price: 105,
      medias: null,
    },
    {
      id: uuidv4(),
      name: `Brigadeiro de cranberry com frutas cristalizadas`,
      description: undefined,
      price: 110,
      medias: null,
    },
    {
      id: uuidv4(),
      name: `Brigadeiro de leite ninho`,
      description: undefined,
      price: 105,
      medias: null,
    },
    {
      id: uuidv4(),
      name: `Brigadeiro de limão`,
      description: undefined,
      price: 105,
      medias: null,
    },
    {
      id: uuidv4(),
      name: `Brigadeiro de oreo`,
      description: undefined,
      price: 105,
      medias: null,
    },
    {
      id: uuidv4(),
      name: `Brigadeiro de pistache`,
      description: undefined,
      price: 110,
      medias: null,
    },
    {
      id: uuidv4(),
      name: `Brigadeiro tradicional`,
      description: undefined,
      price: 105,
      medias: null,
    },
    {
      id: uuidv4(),
      name: `Camafeu (Brigadeiro de Nozes)`,
      description: undefined,
      price: 110,
      medias: null,
    },
    {
      id: uuidv4(),
      name: `Doce de abacaxi`,
      description: undefined,
      price: 110,
      medias: null,
    },
    {
      id: uuidv4(),
      name: `Doce de damasco`,
      description: undefined,
      price: 105,
      medias: null,
    },
    {
      id: uuidv4(),
      name: `Goiabada`,
      description: undefined,
      price: 105,
      medias: null,
    },
    {
      id: uuidv4(),
      name: `Nutella`,
      description: undefined,
      price: 105,
      medias: null,
    },
    {
      id: uuidv4(),
      name: `Brigadeiro Tradicional com Cerejas`,
      description: undefined,
      price: 110,
      medias: null,
    },
    {
      id: uuidv4(),
      name: `Nutella com Amêndoas Laminadas`,
      description: undefined,
      price: 110,
      medias: null,
    },
    {
      id: uuidv4(),
      name: `Brigadeiro de Leite Ninho com Amêndoas Laminadas`,
      description: undefined,
      price: 110,
      medias: null,
    },
  ],
  batters: [
    `Amendoim`,
    `Café`,
    `Chocolate`,
    `Limão`,
    `Morango`,
    `Nozes`,
    `Tradicional`,
  ],
  chocolates: null,
  quantityOptions: [
    {
      id: uuidv4(),
      type: `Receita inteira`,
      mass: `1Kg`,
      quantity: 200,
      price: undefined,
    },
    {
      id: uuidv4(),
      type: `Meia receita`,
      mass: `500g`,
      quantity: 100,
      price: 74,
    },
    {
      id: uuidv4(),
      type: `Receita inteira com 2 sabores diferentes`,
      mass: `1Kg`,
      quantity: 200,
      price: 120,
    },
  ],
  colorOptions: null,
};

const stuffedCandyBullets: BulletsProps = {
  id: uuidv4(),
  title: `Balas de Bombom Recheadas`,
  description: `Balas de coco de bombom recheadas`,
  flavors: [
    {
      id: uuidv4(),
      name: `Bicho de pé (Brigadeiro de Morango)`,
      description: undefined,
      price: 140,
      medias: null,
    },
    {
      id: uuidv4(),
      name: `Brigadeiro de cereja`,
      description: undefined,
      price: 140,
      medias: null,
    },
    {
      id: uuidv4(),
      name: `Brigadeiro branco`,
      description: undefined,
      price: 140,
      medias: null,
    },
    {
      id: uuidv4(),
      name: `Brigadeiro de beijinho`,
      description: undefined,
      price: 140,
      medias: null,
    },
    {
      id: uuidv4(),
      name: `Brigadeiro de cranberry com frutas cristalizadas`,
      description: undefined,
      price: 140,
      medias: null,
    },
    {
      id: uuidv4(),
      name: `Brigadeiro de leite ninho`,
      description: undefined,
      price: 140,
      medias: null,
    },
    {
      id: uuidv4(),
      name: `Brigadeiro de limão`,
      description: undefined,
      price: 140,
      medias: null,
    },
    {
      id: uuidv4(),
      name: `Brigadeiro de oreo`,
      description: undefined,
      price: 140,
      medias: null,
    },
    {
      id: uuidv4(),
      name: `Brigadeiro de pistache`,
      description: undefined,
      price: 140,
      medias: null,
    },
    {
      id: uuidv4(),
      name: `Brigadeiro tradicional`,
      description: undefined,
      price: 140,
      medias: null,
    },
    {
      id: uuidv4(),
      name: `Camafeu (Brigadeiro de Nozes)`,
      description: undefined,
      price: 140,
      medias: null,
    },
    {
      id: uuidv4(),
      name: `Doce de abacaxi`,
      description: undefined,
      price: 140,
      medias: null,
    },
    {
      id: uuidv4(),
      name: `Doce de damasco`,
      description: undefined,
      price: 140,
      medias: null,
    },
    {
      id: uuidv4(),
      name: `Goiabada`,
      description: undefined,
      price: 140,
      medias: null,
    },
    {
      id: uuidv4(),
      name: `Nutella`,
      description: undefined,
      price: 140,
      medias: null,
    },
    {
      id: uuidv4(),
      name: `Brigadeiro Tradicional com Cerejas`,
      description: undefined,
      price: 140,
      medias: null,
    },
    {
      id: uuidv4(),
      name: `Nutella com Amêndoas Laminadas`,
      description: undefined,
      price: 140,
      medias: null,
    },
    {
      id: uuidv4(),
      name: `Brigadeiro de Leite Ninho com Amêndoas Laminadas`,
      description: undefined,
      price: 140,
      medias: null,
    },
  ],
  batters: [
    `Amendoim`,
    `Café`,
    `Chocolate`,
    `Limão`,
    `Morango`,
    `Nozes`,
    `Tradicional`,
  ],
  chocolates: [`Ao leite`, `Meio amargo`, `Blend (Amargo e Ao Leite)`],
  quantityOptions: [
    {
      id: uuidv4(),
      type: `Receita inteira`,
      mass: `1Kg`,
      quantity: 120,
      price: undefined,
    },
    {
      id: uuidv4(),
      type: `Meia receita`,
      mass: `500g`,
      quantity: 60,
      price: 104,
    },
    {
      id: uuidv4(),
      type: `Receita inteira com 2 sabores diferentes`,
      mass: `1Kg`,
      quantity: 120,
      price: 150,
    },
  ],
  colorOptions: null,
};

const candyBulletsWithoutilling: BulletsProps = {
  id: uuidv4(),
  title: `Balas de Bombom S/Recheio`,
  description: `Balas de coco de bombom sem recheio`,
  flavors: [
    {
      id: uuidv4(),
      name: `Amendoim`,
      description: undefined,
      price: 120,
      medias: null,
    },
    {
      id: uuidv4(),
      name: `Café`,
      description: undefined,
      price: 120,
      medias: null,
    },
    {
      id: uuidv4(),
      name: `Chocolate`,
      description: undefined,
      price: 120,
      medias: null,
    },
    {
      id: uuidv4(),
      name: `Limão`,
      description: undefined,
      price: 120,
      medias: null,
    },
    {
      id: uuidv4(),
      name: `Morango`,
      description: undefined,
      price: 120,
      medias: null,
    },
    {
      id: uuidv4(),
      name: `Nozes`,
      description: undefined,
      price: 120,
      medias: null,
    },
    {
      id: uuidv4(),
      name: `Tradicional`,
      description: undefined,
      price: 120,
      medias: null,
    },
  ],
  batters: null,
  chocolates: [`Ao leite`, `Meio amargo`, `Blend (Amargo e Ao Leite)`],
  quantityOptions: [
    {
      id: uuidv4(),
      type: `Receita inteira`,
      mass: `1Kg`,
      quantity: 120,
      price: undefined,
    },
    {
      id: uuidv4(),
      type: `Meia receita`,
      mass: `500g`,
      quantity: 60,
      price: 84,
    },
    {
      id: uuidv4(),
      type: `Receita inteira com 2 sabores diferentes`,
      mass: `1Kg`,
      quantity: 120,
      price: 130,
    },
  ],
  colorOptions: null,
};

export const colorfulDryBullets: BulletsProps = {
  id: uuidv4(),
  title: `Balas Sequinhas Coloridas`,
  description: `Balas de coco sequinhas coloridas`,
  flavors: [
    {
      id: uuidv4(),
      name: `Amendoim`,
      description: undefined,
      price: 120,
      medias: null,
    },
    {
      id: uuidv4(),
      name: `Café`,
      description: undefined,
      price: 120,
      medias: null,
    },
    {
      id: uuidv4(),
      name: `Tradicional`,
      description: undefined,
      price: 70,
      medias: null,
    },
  ],
  batters: null,
  chocolates: null,
  quantityOptions: [
    {
      id: uuidv4(),
      type: `Receita inteira`,
      mass: `1Kg`,
      quantity: 220,
      price: undefined,
    },
  ],
  colorOptions: [
    {
      name: `Amarelo Damasco`,
      color: `#e4c100`,
    },
    {
      name: `Amarelo Gema`,
      color: `#eca000`,
    },
    {
      name: `Azul Anis`,
      color: `#008ede`,
    },
    {
      name: `Azul Jeans`,
      color: `#105cb6`,
    },
    {
      name: `Branco Leite`,
      color: `#e8e8e8`,
    },
    {
      name: `Laranja`,
      color: `#f48e00`,
    },
    {
      name: `Marrom Chocolate`,
      color: `#a24600`,
    },
    {
      name: `Marrom`,
      color: `#3f0a00`,
    },
    {
      name: `Pink`,
      color: `#d01467`,
    },
    {
      name: `Preto Ameixa`,
      color: `#050505`,
    },
    {
      name: `Rosa Cereja`,
      color: `#d9327a`,
    },
    {
      name: `Roxo Batata`,
      color: undefined,
    },
    {
      name: `Salmão`,
      color: `#d09530`,
    },
    {
      name: `Verde Folha`,
      color: `#41932a`,
    },
    {
      name: `Verde Hortelã`,
      color: `#00a32f`,
    },
    {
      name: `Verde Limão`,
      color: `#6fab0b`,
    },
    {
      name: `Vermelho Morango`,
      color: `#d01a13`,
    },
    {
      name: `Vermelho Natal`,
      color: `#a41621`,
    },
    {
      name: `Vinho Bordô`,
      color: `#900b4d`,
    },
    {
      name: `Violeta`,
      color: `#4823a8`,
    },
    {
      name: `Preto Intenso`,
      color: undefined,
    },
  ],
};

export const bullets: BulletsProps[] = [
  traditionalIcedBullets,
  traditionalDryBullets,
  stuffedIcedBullets,
  stuffedDryBullets,
  stuffedCandyBullets,
  candyBulletsWithoutilling,
  colorfulDryBullets,
];
